export function detectLanguageByExtension(ext: string): string {
  const map: Record<string, string> = {
    // Programming Languages
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".py": "python",
    ".java": "java",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".hpp": "cpp",
    ".c": "c",
    ".h": "c",
    ".cs": "csharp",
    ".rb": "ruby",
    ".php": "php",
    ".go": "go",
    ".rs": "rust",
    ".swift": "swift",
    ".kt": "kotlin",
    ".dart": "dart",
    ".sql": "sql",
    ".pl": "perl",
    ".scala": "scala",
    ".m": "objective-c",
    ".mm": "objective-c",
    ".asm": "assembly",

    // Web Technologies
    ".vue": "vue",
    ".svelte": "svelte",
    ".jsp": "jsp",
    ".asp": "asp",
    ".less": "less",
    ".scss": "scss",
    ".sass": "scss",
    ".html": "html",
    ".htm": "html",
    ".css": "css",

    // Data & Config Files
    ".csv": "csv",
    ".tsv": "tsv",
    ".xls": "excel",
    ".xlsx": "excel",
    ".ods": "excel",
    ".log": "log",
    ".txt": "text",
    ".json": "json",
    ".xml": "xml",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".conf": "config",

    // Documentation
    ".md": "markdown",
    ".markdown": "markdown",
    ".rst": "restructuredtext",
    ".tex": "latex",

    // Shell Scripts
    ".bash": "shell",
    ".zsh": "shell",
    ".fish": "shell",
    ".ksh": "shell",
    ".sh": "shell",
    ".cmd": "batch",
    ".bat": "batch",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
    ".ps1xml": "powershell",
    ".pssc": "powershell",
    ".psrc": "powershell",

    // Common Types
    ".sqlite": "sqlite",
    ".db": "database",
    ".r": "r",
    ".gradle": "gradle",
    ".dockerfile": "dockerfile",
    ".env": "env",
    ".gitignore": "gitignore",
  };
  return map[ext] || "text";
}
